const mongoose = require('mongoose');
const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.resolve(__dirname, '.env') });
const mongoUri = process.env.MONGODB_URI;

async function runExplain() {
    await mongoose.connect(mongoUri);
    const db = mongoose.connection.db;
    
    // exact query structure generated by controller for search='test'
    // let's assume team visible filter applied
    const query = {
        $and: [
            {
               $or: [
                   { 'visibleTo': 'Everyone' },
                   { 'assignment.visibleTo': 'Everyone' },
                   { 'visibleTo': 'Team', 'teams': new mongoose.Types.ObjectId('6991ad69e07eb3dd7dd46681') },
                   { 'assignment.visibleTo': 'Team', 'assignment.team': new mongoose.Types.ObjectId('6991ad69e07eb3dd7dd46681') },
                   { 'owner': new mongoose.Types.ObjectId('69c4be0fd8c5cd0d6c90e999') },
                   { 'assignment.assignedTo': new mongoose.Types.ObjectId('69c4be0fd8c5cd0d6c90e999') }
               ]
            },
            {
               isVisible: { $ne: false },
               stage: { $nin: ['Closed Won', 'Closed Lost', 'Cancelled', 'Closed', 'Sold Out'] },
               $or: [
                    { dealId: { $regex: 'test', $options: 'i' } },
                    { unitNo: { $regex: 'test', $options: 'i' } },
                    { location: { $regex: 'test', $options: 'i' } },
                    { projectName: { $regex: 'test', $options: 'i' } }
               ]
            }
        ]
    };

    console.log("=== EXPLAIN FIND ===");
    const findExplain = await db.collection('deals').find(query).sort({ updatedAt: -1 }).limit(25).explain('executionStats');
    console.log("Execution Time (Find):", findExplain.executionStats.executionTimeMillis);
    console.log("Total Docs Examined:", findExplain.executionStats.totalDocsExamined);
    
    console.log("\n=== EXPLAIN COUNT ===");
    const countExplain = await db.collection('deals').find(query).explain('executionStats');
    console.log("Execution Time (Count):", countExplain.executionStats.executionTimeMillis);
    console.log("Total Docs Examined:", countExplain.executionStats.totalDocsExamined);
    
    console.log("\n=== INDEXES ===");
    const indexes = await db.collection('deals').indexes();
    console.log(indexes.map(idx => idx.name));
    
    process.exit(0);
}
runExplain().catch(console.error);
