import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawDataPath = path.join(__dirname, '../data/raw_india_pincodes.json');
const outputPath = path.join(__dirname, '../data/detailedLocationData.js');

try {
    console.log('Reading raw data...');
    const rawContent = fs.readFileSync(rawDataPath, 'utf8');
    // Remove BOM if present
    const cleanContent = rawContent.replace(/^\uFEFF/, '');
    const data = JSON.parse(cleanContent);

    // The dataset is wrapped in "Sheet1" or might be an array directly depending on exact file
    const records = data.Sheet1 || data;

    if (!Array.isArray(records)) {
        throw new Error("Data is not an array and no Sheet1 key found");
    }

    console.log(`Processing ${records.length} records...`);

    const hierarchy = {};

    records.forEach(record => {
        const state = record.State;
        const district = record.District;
        // Use City as Tehsil/Sub-District level. Fallback to 'Main' if missing.
        const city = record.City === 'NA' || !record.City ? 'Main' : record.City;
        const office = record.PostOfficeName;
        const pincode = String(record.Pincode);

        if (!state || !district || !office || !pincode) return;

        if (!hierarchy[state]) {
            hierarchy[state] = {};
        }
        if (!hierarchy[state][district]) {
            hierarchy[state][district] = {};
        }
        if (!hierarchy[state][district][city]) {
            hierarchy[state][district][city] = [];
        }

        // Avoid duplicates if same office exists with same pincode
        const existing = hierarchy[state][district][city].find(o => o.name === office && o.pincode === pincode);
        if (!existing) {
            hierarchy[state][district][city].push({ name: office, pincode: pincode });
        }
    });

    // Sort keys for better UX (optional, but good)
    const sortedHierarchy = {};
    Object.keys(hierarchy).sort().forEach(state => {
        sortedHierarchy[state] = {};
        Object.keys(hierarchy[state]).sort().forEach(district => {
            sortedHierarchy[state][district] = {};
            Object.keys(hierarchy[state][district]).sort().forEach(city => {
                // sort post offices by name
                sortedHierarchy[state][district][city] = hierarchy[state][district][city].sort((a, b) => a.name.localeCompare(b.name));
            });
        });
    });

    const fileContent = `// This file is auto-generated by src/scripts/processPincodes.js
export const INDIAN_LOCATION_HIERARCHY = ${JSON.stringify(sortedHierarchy, null, 2)};
`;

    console.log('Writing output file...');
    fs.writeFileSync(outputPath, fileContent);
    console.log('Success! detailedLocationData.js has been updated.');

} catch (err) {
    console.error('Error processing data:', err);
}
