import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { renderValue } from './renderUtils';

export const generateDealsPDF = (deals, leadName = 'Valued Client') => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); // Slate 800
    doc.text('Premium Property Portfolio', 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text(`Prepared exclusively for: ${leadName}`, 14, 30);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 36);
    
    // Add a horizontal line
    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.setLineWidth(0.5);
    doc.line(14, 42, 196, 42);

    if (!deals || deals.length === 0) {
        doc.setFontSize(12);
        doc.text("No properties selected for this portfolio.", 14, 55);
        doc.save('Property_Portfolio.pdf');
        return;
    }

    const tableColumn = ["#", "Project Name", "Location", "Type", "Size", "Price", "Match %"];
    const tableRows = [];

    deals.forEach((item, index) => {
        // Resolve lookup strings if needed. Assuming renderValue handles objects safely if passed
        // For PDF we just want simple strings
        const locationStr = item.inventoryId?.address?.locality || item.inventoryId?.address?.area || item.inventoryId?.address?.location || item.location || 'N/A';
        const typeStr = item.propertyType || item.type || 'N/A';
        const sizeStr = item.sizeConfig || item.size || 'N/A';
        const priceStr = item.price ? `Rs. ${item.price}` : 'N/A';
        
        // Clean up strings by removing objects if any sneaked in
        const cleanStr = (val) => typeof val === 'object' ? JSON.stringify(val) : String(val);

        const rowData = [
            (index + 1).toString(),
            cleanStr(item.projectName || 'Premium Listing'),
            cleanStr(locationStr),
            cleanStr(typeStr),
            cleanStr(sizeStr),
            cleanStr(priceStr),
            `${item.matchPercentage || 0}%`
        ];
        tableRows.push(rowData);
    });

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 50,
        theme: 'grid',
        headStyles: {
            fillColor: [37, 99, 235], // Blue 600
            textColor: 255,
            fontSize: 10,
            fontStyle: 'bold',
            halign: 'center'
        },
        bodyStyles: {
            fontSize: 9,
            textColor: [51, 65, 85] // Slate 700
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252] // Slate 50
        },
        columnStyles: {
            0: { halign: 'center', cellWidth: 10 }, // Index
            1: { cellWidth: 40 }, // Project
            2: { cellWidth: 40 }, // Location
            3: { cellWidth: 25 }, // Type
            4: { cellWidth: 25 }, // Size
            5: { halign: 'right', cellWidth: 25 }, // Price
            6: { halign: 'center', cellWidth: 20 }  // Match %
        },
        margin: { top: 50, right: 14, bottom: 20, left: 14 }
    });
    
    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate 400
        doc.text(
            `Page ${i} of ${pageCount} - Generated by Bharat Properties CRM`,
            doc.internal.pageSize.width / 2,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
    }

    doc.save(`Property_Portfolio_${leadName.replace(/\s+/g, '_')}.pdf`);
};
